version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=itgrowsbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d itgrowsbot"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - app-network

  web:
    build: .
    command: bash collectstatic.sh
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - ./static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/itgrowsbot
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_API_URL=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db
      - redis
      - ollama
    networks:
      - app-network

  celery:
    build: .
    command: celery -A itgrowsbot worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - web
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key
      - DB_NAME=itgrowsbot
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=itgrowsbot.settings
    networks:
      - app-network

  celery-beat:
    build: .
    command: celery -A itgrowsbot beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - celery
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key
      - DB_NAME=itgrowsbot
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=itgrowsbot.settings
    networks:
      - app-network

  bot:
    build: .
    command: python manage.py run_bot
    entrypoint: /app/bot-entrypoint.sh
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - ollama
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key
      - DB_NAME=itgrowsbot
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_API_URL=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      - DJANGO_SETTINGS_MODULE=itgrowsbot.settings
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  ollama_data:
  staticfiles:

networks:
  app-network:
    driver: bridge 