# Generated by Django 5.0.2 on 2025-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название модели Ollama', max_length=100, verbose_name='Model Name')),
                ('is_installed', models.BooleanField(default=False, help_text='Установлена ли модель', verbose_name='Is Installed')),
                ('size', models.CharField(blank=True, help_text='Размер модели', max_length=50, null=True, verbose_name='Size')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Время последнего обновления', verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=False, help_text='Активна ли модель', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Ollama Model',
                'verbose_name_plural': 'Ollama Models',
                'ordering': ['-is_active', '-last_updated'],
            },
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='local_model_name',
            field=models.CharField(default='tinyllama', help_text='Название локальной модели Ollama', max_length=100, verbose_name='Local Model Name'),
        ),
    ]
