# Generated by Django 5.2 on 2025-04-08 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_topic_options_remove_topic_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram Settings', 'verbose_name_plural': 'Telegram Settings'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='openai_api_key',
        ),
        migrations.CreateModel(
            name='OpenAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='API key from OpenAI platform', max_length=255, verbose_name='API Key')),
                ('model', models.CharField(default='gpt-3.5-turbo', help_text='OpenAI model to use for generation', max_length=50, verbose_name='Model')),
                ('temperature', models.FloatField(default=0.7, help_text='Controls randomness in the output (0.0-1.0)', verbose_name='Temperature')),
                ('max_tokens', models.IntegerField(default=2000, help_text='Maximum number of tokens in the response', verbose_name='Max Tokens')),
                ('is_active', models.BooleanField(default=True, help_text='Only one settings instance can be active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openai_settings', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'OpenAI Settings',
                'verbose_name_plural': 'OpenAI Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
