# Generated by Django 4.2.10 on 2025-04-15 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0005_add_priority_to_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ollamamodel',
            options={'verbose_name': 'Ollama Model', 'verbose_name_plural': 'Ollama Models'},
        ),
        migrations.AlterModelOptions(
            name='openaisettings',
            options={'verbose_name': 'OpenAI Settings', 'verbose_name_plural': 'OpenAI Settings'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.RemoveField(
            model_name='ollamamodel',
            name='size',
        ),
        migrations.AlterField(
            model_name='ollamamodel',
            name='details',
            field=models.JSONField(blank=True, help_text='Additional model details from Ollama', null=True),
        ),
        migrations.AlterField(
            model_name='ollamamodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this model'),
        ),
        migrations.AlterField(
            model_name='ollamamodel',
            name='is_installed',
            field=models.BooleanField(default=False, help_text='Whether the model is installed in Ollama'),
        ),
        migrations.AlterField(
            model_name='ollamamodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ollamamodel',
            name='name',
            field=models.CharField(help_text='Name of the Ollama model', max_length=255),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='api_key',
            field=models.CharField(help_text='Your OpenAI API key', max_length=255),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='frequency_penalty',
            field=models.FloatField(default=0.0, help_text='Penalizes repeated token sequences'),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable OpenAI settings'),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='local_model_name',
            field=models.CharField(blank=True, help_text='Name of the local Ollama model to use', max_length=255),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='max_tokens',
            field=models.IntegerField(default=2000, help_text='Maximum number of tokens to generate'),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='presence_penalty',
            field=models.FloatField(default=0.0, help_text='Penalizes repeated tokens'),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='Controls randomness in generation (0.0 to 1.0)'),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='top_p',
            field=models.FloatField(default=1.0, help_text='Controls diversity via nucleus sampling'),
        ),
        migrations.AlterField(
            model_name='openaisettings',
            name='use_local_model',
            field=models.BooleanField(default=False, help_text='Use local Ollama model instead of OpenAI'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='The generated content of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False, help_text='Whether the post has been edited'),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', help_text='Select the language for this post', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number means higher priority for publishing'),
        ),
        migrations.AlterField(
            model_name='post',
            name='progress',
            field=models.IntegerField(default=0, help_text='Generation progress in percentage'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When the post was published', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready to Publish'), ('published', 'Published'), ('failed', 'Failed')], default='draft', help_text='Current status of the post', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='telegram_message_id',
            field=models.IntegerField(blank=True, help_text='ID of the message in Telegram', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(help_text='Select the topic for this post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bot.topic'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable the bot'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='telegram_bot_token',
            field=models.CharField(help_text='Your Telegram bot token', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='telegram_channel_id',
            field=models.CharField(help_text='ID of your Telegram channel', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(help_text='Enter a brief description of the topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text='Enter a topic name', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ] 