# Generated by Django 4.2.10 on 2025-04-15 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0006_update_model_options_and_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_interval', models.CharField(choices=[('hourly', 'Every Hour'), ('daily', 'Once Daily'), ('weekly', 'Once Weekly'), ('custom', 'Custom Interval')], default='daily', help_text='How often to publish new content', max_length=10)),
                ('custom_interval', models.IntegerField(blank=True, help_text='Custom interval in hours (only used if publish_interval is "custom")', null=True)),
                ('publish_time', models.TimeField(default='09:00', help_text='Time of day to publish content (in UTC)')),
                ('max_posts_per_day', models.IntegerField(default=1, help_text='Maximum number of posts to publish per day')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable the scheduler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduler Settings',
                'verbose_name_plural': 'Scheduler Settings',
            },
        ),
    ]
