# Generated by Django 4.2.10 on 2025-04-15 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0009_topic_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaisettings',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openai_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openaisettings',
            name='model',
            field=models.CharField(default='gpt-4', help_text='The OpenAI model to use', max_length=50),
        ),
    ]
